### ISSUE TITLE
plugins的whatcms.py问题

### ISSUE THREAD

**Issue by Hotsunrize** [boy-hack/w12scan-client#2]
https://github.com/boy-hack/w12scan-client/blob/1ed5cc90a61191933e63a779de0298be42e14a39/plugins/whatcms.py#L37
应该去掉这个括号
<pre>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'bytes' object is not callable
</pre>

**Comment by boy-hack** [comment]
thanks
